- targets:
    - 10.0.0.53:9100
  labels:
    hostname: nscache1.example.invalid

- targets:
    - 10.0.0.54:9100
  labels:
    hostname: ns1.example.invalid

- targets:
    - 192.168.20.53:9100
  labels:
    hostname: ns2.example.invalid
